name: 'fuzzyoct-action'
description: 'comments on commits'
author: 'muachilin'
inputs:
  github-token:
    description: 'Github token'
    required: true
  commit-comment:
    description: 'The message print on comment when adding commits'
    default: 'Successfully commit! ✨'
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: cloud-snow
  color: red
