name: 'pig-action'
description: 'Make Pull requests and Issues Glue together.'
author: 'muachilin'
inputs:
  github-token:
    description: 'Github Token'
    required: true
  in-progress-label-word:
    description: 'The text of the label indicating that the issue is in progress.'
    required: false
    default: "in progress 🌱"
  in-progress-label-color:
    description: 'The color of the label indicating that the issue is in progress.'
    required: false
    default: "ffc163"
  done-label-word:
    description: 'The text of the label indicating that the issue is solved.'
    required: false
    default: "done 🎉"
  done-label-color:
    description: 'The color of the label indicating that the issue is solved.'
    required: false
    default: "c0ff33"
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: cloud-snow
  color: red
