name: 'fuzzyocto-action'
description: 'The bridge between issues and pull requests'
author: 'muachilin'
inputs:
  github-token:
    description: 'Github Token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: cloud-snow
  color: red
